# Site settings
short_title: OpenDevStack
title: OpenDevStack
description: >
  OpenDevStack is a framework to help in setting up project infrastructure and CD processes on OpenShift and Atlassian toolstack with one click.

# Twitter
twitter:
  username: opendevstack

# GitHub (required for local site builds)
github:
  owner_name: opendevstack
  repository_name: opendevstack.github.io
  repository_url: https://github.com/opendevstack/opendevstack.github.io
  organization: https://github.com/opendevstack

# Build settings
baseurl:
permalink: doc/:title
markdown: kramdown
highlighter: rouge
relative_permalinks: false
collections:
  doc:
    output: true
 
# this must be excluded for the gradle build
# otherwise jekyll tries to source this directory as well
# ... and failes ..
exclude: [build]
